defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 2
  username: aporter
  password:

development:
  database: sample_app_development
  <<: *defaults

test: &test
  database: sample_app_test
  <<: *defaults
